# Data and pipeline visualization

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from scipy import stats, integrate


%matplotlib inlinefr
sns.set(color_codes=True)
pd.options.mode.chained_assignment = None 

# data loading
path = '../datasets/preprocessed/'
# dfrat     = pd.read_hdf(path+'relationalDatabase.h5', 'Rat_Behavior').set_index('index')

dfrat     = pd.read_hdf(path+'filteredDatabase.h5', 'Rat_Behavior').set_index('index')
dfevent   = pd.read_hdf(path+'relationalDatabase.h5', 'Events').set_index('index')
dfsession = pd.read_hdf(path+'relationalDatabase.h5', 'Sessions')

In [4]:
dfrat.describe()

,Frame,Time,X_Pos,Y_Pos,Z_Pos,X_Ori,Y_Ori,Z_Ori,session_id
count,764556.000000,764556.000000,764556.000000,764556.000000,764556.000000,764556.000000,764556.000000,764556.000000,764556.000000
mean,97688.622187,407.035952,0.000362,0.097558,-0.021076,-0.040256,-0.140115,-0.092203,3.444674
std,54438.593256,226.827486,0.051046,0.013420,0.054835,0.632538,0.247596,0.699416,2.104154
min,84.000000,0.350000,-0.090846,0.070121,-0.099633,-0.998370,-0.749259,-0.999698,0.000000
25%,54564.000000,227.350014,-0.047613,0.087332,-0.072306,-0.634764,-0.315030,-0.789738,2.000000
50%,96764.000000,403.183359,-0.002463,0.096860,-0.030191,-0.062903,-0.123643,-0.209676,3.000000
75%,135957.000000,566.487536,0.041970,0.108511,0.027843,0.558697,0.032182,0.628345,5.000000
max,245002.000000,1020.841732,0.121504,0.129796,0.080537,0.999889,0.548486,0.999899,7.000000